### ISSUE TITLE
[Remote mode] Update interval is about +10 seconds off sync

### ISSUE THREAD

**Issue by kentala** [framelabs-eu/firmware#1]
The update interval lags behind about 10-14 seconds per update. I suspect it takes about this time for the device to wake up, fetch the image, update the screen and go back to sleep. If this is the case, can the delay be subtracted from the sleep timer?

**Comment by clashman** [comment]
You can just enter floating point values for the interval to increase the precision.

If you need to make up for the fluctuating time it takes to fetch remote content, you can set the Cache-Control header to change the interval.

Example code here: https://github.com/framelabs-eu/imageserver/blob/a7780cb1e3fd2ac4cdd3926754ea244bb2a0f8a7/examples/vlc_cover_server/vlc_cover_server.py#L23
