### ISSUE TITLE
add basic authentication to the http client

### ISSUE THREAD

**Issue by JensWalter** [framelabs-eu/firmware#4]
The current interface for web retrieval is working fine for local deployments of the server. What I would like to do is put the server on a public endpoint. Modifying the server is not an issue, since the python script is available. For the client however I found no sources available, hence this ticket.
To call a public endpoint, I would require 2 things, some form of authentication (where basic auth is probably the easiest) and TLS support.

If there is anything I can do to support this endeavor please let me know.

**Comment by clashman** [comment]
That would imply dynamic certificate management and a synced clock to be able to handle revoked certificates, right?

**Comment by JensWalter** [comment]
Yes, absolutely, I think it is not worth it to do a certificate chain management and revocation stuff. I am not sure whether the frame has a clock, so from my point of view accepting an expired certificate (because there is no clock) is also fine.

**Comment by clashman** [comment]
Since the path after the domain of a https GET request is encrypted, couldn't you simply use that as a workaround?

i.e. set the image server URL to "https://YOURDOMAIN/foobar?user=X&password=Y'

Since there is no certificate checking at the moment, the mechanism is obviously susceptible to MitM attacks, so you should not reuse your banking login as username + password. But apart from that, wouldn't that work for you?

**Comment by JensWalter** [comment]
Yes, that is fine too, as long as the get parameters aren't used for anything else I am totally fine with transferring the credentials this way.
As you said, this is not a bulletproof solution, but for me convenience is key.

On a side note, I am currently working on the server part as a Rust/axum server that I would deploy to Google Cloud Run. So far it is not working (something wrong with the image encoding) and I haven't found the time to debug the output. As soon as I have a working version I will put the code on github.

**Comment by clashman** [comment]
Cool. I am closing this issue then.

Let me know when your rust implementation works. Probably it makes sense to publish a list of derived user projects in the future.
